# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'DaDaCook' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DaDaCook

pod 'Masonry'
pod 'AFNetworking'
pod 'YYKit'
pod 'BlocksKit'
pod 'MBProgressHUD'
pod 'MJRefresh'
pod 'CocoaLumberjack'
pod 'MLTransition'
pod 'iCarousel'
pod 'pop'

end
